import "./globals.css";
import type { Metadata } from "next";
import { Provider, Stack, ThemeProvider, ThemeToggle } from "@constants/components";
import "../public/assets/fonts/fontawesome.css";
import { Toaster } from "@/components/ui/toaster";

import { Inter } from "next/font/google";
import NavigationBar from "@/components/custom/navigation/NavigationBar";

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={"h-[100dvh] text-[14px]"}>
      <body className={`${inter.className} h-full`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Provider>
            <Stack className={'h-full'}>
              <NavigationBar />
              <Stack className={'h-[calc(100%-35px)]'}>{children}</Stack>
            </Stack>
            <Toaster />
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
